'use strict';


angular.module('app', [
    'ngAnimate',
    'ngAside',
    'ngAria',
    'ngCookies',
    'ngMessages',
    'ngResource',
    'ngSanitize',
    'ngTouch',
    'ngStorage',
    'ui.router',
    'ui.utils',
    'ui.load',
    'ui.bootstrap',
    'ui.jq',
    'oc.lazyLoad',
    'ngFileUpload',
    'angularUtils.directives.dirPagination',
    'angular-button-spinner',
    'jlareau.bowser',
    'facebook',
    'google-signin',
    'angucomplete',
    'anguvideo',
    'ismobile',
    'firebase',
    'slickCarousel',
    'ngNotify',
    'angularMoment',
    'infinite-scroll',
    'ui.select',
    'AnimatedScroll',
    'duScroll',
    'skitter',
    'angular-web-notification',
    'chart.js',
    'cp.ngConfirm'
]);
